# Generated by Django 2.1.5 on 2019-01-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_iscomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='isComplete',
        ),
    ]
